name: Release Charts
on:
  workflow_call:
    inputs:
      charts_dir:
        type: string
        required: false
        default: helm
        description: 'Path to the directory with the helm charts'
jobs:
  release:
    name: 'Publish to Github Pages'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0 # need full history for chart releaser to detect changes and release charts
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.1
      - name: Add Helm Repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add k8s-at-home https://k8s-at-home.com/charts
          helm repo add groundhog2k https://groundhog2k.github.io/helm-charts/
          helm repo add psa https://bryopsida.github.io/psa-restricted-patcher/
          helm repo update
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@main
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          charts_dir: ${{ inputs.charts_dir }}