name: Node Typescript QA
on: 
  workflow_call:
    inputs:
      node_versions:
        default: '{"node-version": ["16.x","18.x","20.x"]}'
        type: string
        required: false
      continue-on-prod-vulns:
        default: false
        type: boolean
        description: 'Whether to fail the job or continue when vulnerabilities are found in production dependencies'
      runs-on:
        type: 'string'
        required: false
        default: '["ubuntu-latest"]'
        description: string of a JSON array describing the run target.
jobs:
  build-and-test:
    name: Build And Test
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON( inputs.node_versions ) }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint --if-present
      - run: npm audit --omit dev
        continue-on-error: ${{ inputs.continue-on-prod-vulns }}
      - run: npm test
      - uses: actions/upload-artifact@v4
        if: ${{ matrix.node-version == '16.x' }}
        with:
          name: coverage
          path: |
            coverage