name: Node Typescript QA
on: 
  workflow_call:
    inputs:
      node_versions:
        default: '{"node-version": ["18.x","20.x", "22.x"]}'
        type: string
        required: false
      continue-on-prod-vulns:
        default: false
        type: boolean
        description: 'Whether to fail the job or continue when vulnerabilities are found in production dependencies'
jobs:
  build-and-test:
    name: Build And Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON( inputs.node_versions ) }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint --if-present
      - run: npm audit --omit dev
        continue-on-error: ${{ inputs.continue-on-prod-vulns }}
      - run: npm test
      - uses: actions/upload-artifact@v4
        if: ${{ matrix.node-version == '16.x' }}
        with:
          name: coverage
          path: |
            coverage