name: Test Helm QA

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/helm-qa.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/helm-qa.yml

jobs:
  call-helm-qa:
    name: Verify
    uses: ./.github/workflows/helm-qa.yml
    with:
      charts_dir: test-content/helm-qa/test/charts
